apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:iXU135ZZFbEKsl3snwbzNAZoOg==,iv:ChmyF+L0VLR5W/mekgdRyWUgzOR7leORzcwIkZHYaQc=,tag:2OEC1u+p6A/L/BzBVu0SZQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:A2z2eRyO7Y1mHuzjL50NNhor6vawqViSgrK4YMO8cD+MYZBJcA==,iv:Fb5fL/i/0hGnX6e8/Fsx7Ow35Y/3anhiGPypIF+ojWA=,tag:DKJncI+xJiTonHCQgEmFdA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:ob93C3TVRFfoRM1OdW1y,iv:+n8oLEQdrehjyI1pwnoeAZUdgAkIHmGq2E4rDL199gw=,tag:h5thZYks0lZgF50EhOBMgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rkyznefgw985upa37pup2wavf6qs5v35jvzugx7gd4h7m6d233qszeqqak
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRnErRnBrYURYOG1NQVJv
            OW1UQllHbkFnWnpYVUhrd1p1c05RVkJ1QjA4CmZCdU9uWFVwM1VDcit6eW5CTTk1
            Smo0ZUl2bVNpbUVGVnlGS0VJSVlGaVkKLS0tICtRMENldUNkVjd2SGI1OWxaeENw
            RHZwbnNuek1ud0JNb2ZnUmtsUVB3L2sKKMc7Qbg8INfCgAtudN0y9l5nltAXbHby
            D8Rm19gX/fI4Fd8TJN1cPTEJ4WMJI5yRuN66YwBSOXvm2d0Fw3epaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-13T01:38:39Z"
    mac: ENC[AES256_GCM,data:MnbMkoemKUo/FWgIFosEn2KYhwzz3L726VYarycYoiK8Gec2MLn+yD8+uhKNrGKT9huL7A/2VQ9qmqSf4xucNP4bsRe7Ak1nejdiEPAD38WfUsO8TtDgbc/3HMphhF3T1Mgfx/FfX2kHX3L0dnRyjHZCGx/hLyXwE03f+34g9io=,iv:zdY4G1N9QbBZ1NqXh53hCxDapQLofc7nsNYyGk168jw=,tag:ctyX9XVtID4XOvjiKJn65Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
