---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Los_Angeles"
  KUBE_VIP_ADDR: "10.0.22.200"
  METALLB_LB_RANGE: "10.0.22.220-10.0.22.240"
  METALLB_K8S_GATEWAY_ADDR: "10.0.22.220"
  METALLB_INGRESS_ADDR: "10.0.22.221"
